# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export PATH=/opt/homebrew/bin:$PATH

ZSH_THEME="robbyrussell"

source $ZSH/oh-my-zsh.sh
source ${ZDOTDIR:-$HOME}/dotfiles/zsh/startup

plugins=(
    z
    zsh-autosuggestions
    git-flow
)
